name: Что такое ЭЦП?
description: ЭЦП для чайников. Что это такое. Какие виды ЭЦП бывают. Простая подпись. Усиленная подпись. Неквалифицированная и квалифицированная подпись. Как подписать и как проверить подпись. Как работать с сертификатами для ЭЦП.
